services:
  migrate:
    profiles: ["api-no-docker"]

  api:
    profiles: ["api-no-docker"]

  postgres:
    ports:
      - "127.0.0.1:${POSTGRES_HOST_PORT:-5436}:5432"

  web:
    build:
      args:
        LEGIVEL_API_URL: http://host.docker.internal:8001
    environment:
      LEGIVEL_API_URL: http://host.docker.internal:8001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: !reset {}
